codigo1_win:
	gcc -o codigo1 codigo1.c -ansi -pedantic -Wall -std=c99
	./codigo1
codigo1_linux:
	gcc codigo1.c -o codigo1.out -Wall
	./codigo1.out

codigo2:
	gcc codigo2.c -o codigo2.out -ansi -pedantic -Wall -std=c99
	./codigo2.out