codigo1_win:
	gcc -o codigo1 codigo1.c -ansi -pedantic -Wall
	./codigo1
codigo1_linux:
	gcc codigo1.c -o codigo1.out -Wall
	./codigo1.out

codigo2_win:
	gcc -o codigo2 codigo2.c -ansi -pedantic -Wall
	./codigo1
codigo2_linux:
	gcc codigo2.c -o codigo2.out -Wall
	./codigo2.out