media_par_impar_win:
	gcc -o media_par_impar media_par_impar.c -ansi -pedantic -Wall -std=c99
	./media_par_impar
media_par_impar_linux:
	gcc media_par_impar.c -o media_par_impar.out -Wall
	./media_par_impar.out